### ISSUE TITLE
reply markup size kota desktopda 

### ISSUE THREAD

**Issue by begyy** [azimjohn/ustoztop#1]
![image](https://user-images.githubusercontent.com/44405438/56014769-0c602c00-5d10-11e9-8109-a6d544011eea.png)
telebot.types.ReplyKeyboardMarkup(True,False) qoyish kere

**Comment by azimjohn** [comment]
<img width="635" alt="Screen Shot 2019-06-13 at 1 00 33 PM" src="https://user-images.githubusercontent.com/35038240/59414618-45ce1a00-8ddb-11e9-8c54-9aaec1feb32d.png">
To'g'irlandi 🎉 
@begyy Katta Rahmat!
